### PR TITLE
fix(release): update go version conditional for deploy

### PR DESCRIPTION
**Pull request by Kieran-Muller**
## PR summary

Update conditional go version used in order to trigger release in main.

**Fixes:** n/a

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [x] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  

Travis build is currently skipping deploy step as condition is not met by current go versions in use. 
https://app.travis-ci.com/github/IBM/container-registry-go-sdk/jobs/628344959

## What is the new behavior?  

Travis condition should pass on the main branch and trigger release creation.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Kieran-Muller** [comment]
Travis now correctly triggers pathways that were behind the conditional:
https://app.travis-ci.com/github/IBM/container-registry-go-sdk/jobs/628373965

**Review by brackendawson — CHANGES_REQUESTED** [review]
Use "stable" instead because 1.21 will be removed after "module" is >1.21.

**Comment by Kieran-Muller** [comment]
Stable now triggers conditional steps:
https://app.travis-ci.com/github/IBM/container-registry-go-sdk/jobs/628376553

Not 1.21 https://app.travis-ci.com/github/IBM/container-registry-go-sdk/jobs/628376552

**Review by brackendawson — APPROVED** [review]

**Pull request merged**
